// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changelog.sql

package db

import (
	"context"
	"database/sql"
)

const createChangeLog = `-- name: CreateChangeLog :one
INSERT INTO change_log (
  actor, operation, entity, entity_id, before_json, after_json, description, rollback_of
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, ts, actor, operation, entity, entity_id, before_json, after_json, description, rolled_back, rollback_of
`

type CreateChangeLogParams struct {
	Actor       string         `json:"actor"`
	Operation   string         `json:"operation"`
	Entity      string         `json:"entity"`
	EntityID    sql.NullInt64  `json:"entity_id"`
	BeforeJson  sql.NullString `json:"before_json"`
	AfterJson   sql.NullString `json:"after_json"`
	Description string         `json:"description"`
	RollbackOf  sql.NullInt64  `json:"rollback_of"`
}

func (q *Queries) CreateChangeLog(ctx context.Context, arg CreateChangeLogParams) (ChangeLog, error) {
	row := q.db.QueryRowContext(ctx, createChangeLog,
		arg.Actor,
		arg.Operation,
		arg.Entity,
		arg.EntityID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.Description,
		arg.RollbackOf,
	)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.Actor,
		&i.Operation,
		&i.Entity,
		&i.EntityID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.Description,
		&i.RolledBack,
		&i.RollbackOf,
	)
	return i, err
}

const getChangeLog = `-- name: GetChangeLog :one
SELECT id, ts, actor, operation, entity, entity_id, before_json, after_json, description, rolled_back, rollback_of FROM change_log WHERE id = ?
`

func (q *Queries) GetChangeLog(ctx context.Context, id int64) (ChangeLog, error) {
	row := q.db.QueryRowContext(ctx, getChangeLog, id)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.Actor,
		&i.Operation,
		&i.Entity,
		&i.EntityID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.Description,
		&i.RolledBack,
		&i.RollbackOf,
	)
	return i, err
}

const listChangeLog = `-- name: ListChangeLog :many
SELECT id, ts, actor, operation, entity, entity_id, before_json, after_json, description, rolled_back, rollback_of FROM change_log ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListChangeLog(ctx context.Context, limit int64) ([]ChangeLog, error) {
	rows, err := q.db.QueryContext(ctx, listChangeLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeLog{}
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Actor,
			&i.Operation,
			&i.Entity,
			&i.EntityID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.Description,
			&i.RolledBack,
			&i.RollbackOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChangeRolledBack = `-- name: MarkChangeRolledBack :exec
UPDATE change_log SET rolled_back = 1 WHERE id = ?
`

func (q *Queries) MarkChangeRolledBack(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markChangeRolledBack, id)
	return err
}
