// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: country.sql

package db

import (
	"context"
	"database/sql"
)

const getCountryRule = `-- name: GetCountryRule :one
SELECT id, country_code, country_name, effective_from, effective_to, has_tax_treaty, treaty_in_force_date, treaty_method, treaty_reference, treaty_source_url, standard_withholding_pct, notes, last_updated FROM country_tax_rules
WHERE country_code = ?
  AND effective_from <= ?
  AND (effective_to IS NULL OR effective_to >= ?)
ORDER BY effective_from DESC
LIMIT 1
`

type GetCountryRuleParams struct {
	CountryCode   string        `json:"country_code"`
	EffectiveFrom int64         `json:"effective_from"`
	EffectiveTo   sql.NullInt64 `json:"effective_to"`
}

func (q *Queries) GetCountryRule(ctx context.Context, arg GetCountryRuleParams) (CountryTaxRule, error) {
	row := q.db.QueryRowContext(ctx, getCountryRule, arg.CountryCode, arg.EffectiveFrom, arg.EffectiveTo)
	var i CountryTaxRule
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.CountryName,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.HasTaxTreaty,
		&i.TreatyInForceDate,
		&i.TreatyMethod,
		&i.TreatyReference,
		&i.TreatySourceUrl,
		&i.StandardWithholdingPct,
		&i.Notes,
		&i.LastUpdated,
	)
	return i, err
}

const listAllCountryTaxTypes = `-- name: ListAllCountryTaxTypes :many
SELECT id, country_code, tax_type_code, tax_type_name, description, applies_to, is_creditable_in_norway, default_treatment, basis, typical_rate_pct, effective_from, effective_to FROM country_tax_types
ORDER BY country_code, tax_type_code
`

func (q *Queries) ListAllCountryTaxTypes(ctx context.Context) ([]CountryTaxType, error) {
	rows, err := q.db.QueryContext(ctx, listAllCountryTaxTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountryTaxType{}
	for rows.Next() {
		var i CountryTaxType
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.TaxTypeCode,
			&i.TaxTypeName,
			&i.Description,
			&i.AppliesTo,
			&i.IsCreditableInNorway,
			&i.DefaultTreatment,
			&i.Basis,
			&i.TypicalRatePct,
			&i.EffectiveFrom,
			&i.EffectiveTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountryCodes = `-- name: ListCountryCodes :many
SELECT DISTINCT country_code, country_name FROM country_tax_rules
ORDER BY country_name
`

type ListCountryCodesRow struct {
	CountryCode string `json:"country_code"`
	CountryName string `json:"country_name"`
}

func (q *Queries) ListCountryCodes(ctx context.Context) ([]ListCountryCodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCountryCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountryCodesRow{}
	for rows.Next() {
		var i ListCountryCodesRow
		if err := rows.Scan(&i.CountryCode, &i.CountryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountryRules = `-- name: ListCountryRules :many
SELECT id, country_code, country_name, effective_from, effective_to, has_tax_treaty, treaty_in_force_date, treaty_method, treaty_reference, treaty_source_url, standard_withholding_pct, notes, last_updated FROM country_tax_rules
ORDER BY country_name, effective_from
`

func (q *Queries) ListCountryRules(ctx context.Context) ([]CountryTaxRule, error) {
	rows, err := q.db.QueryContext(ctx, listCountryRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountryTaxRule{}
	for rows.Next() {
		var i CountryTaxRule
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.CountryName,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.HasTaxTreaty,
			&i.TreatyInForceDate,
			&i.TreatyMethod,
			&i.TreatyReference,
			&i.TreatySourceUrl,
			&i.StandardWithholdingPct,
			&i.Notes,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountryTaxTypes = `-- name: ListCountryTaxTypes :many
SELECT id, country_code, tax_type_code, tax_type_name, description, applies_to, is_creditable_in_norway, default_treatment, basis, typical_rate_pct, effective_from, effective_to FROM country_tax_types
WHERE country_code = ?
  AND effective_from <= ?
  AND (effective_to IS NULL OR effective_to >= ?)
ORDER BY tax_type_code
`

type ListCountryTaxTypesParams struct {
	CountryCode   string        `json:"country_code"`
	EffectiveFrom int64         `json:"effective_from"`
	EffectiveTo   sql.NullInt64 `json:"effective_to"`
}

func (q *Queries) ListCountryTaxTypes(ctx context.Context, arg ListCountryTaxTypesParams) ([]CountryTaxType, error) {
	rows, err := q.db.QueryContext(ctx, listCountryTaxTypes, arg.CountryCode, arg.EffectiveFrom, arg.EffectiveTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountryTaxType{}
	for rows.Next() {
		var i CountryTaxType
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.TaxTypeCode,
			&i.TaxTypeName,
			&i.Description,
			&i.AppliesTo,
			&i.IsCreditableInNorway,
			&i.DefaultTreatment,
			&i.Basis,
			&i.TypicalRatePct,
			&i.EffectiveFrom,
			&i.EffectiveTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
