// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: currency.sql

package db

import (
	"context"
)

const getExchangeRate = `-- name: GetExchangeRate :one
SELECT currency, date, rate_nok, source FROM exchange_rates WHERE currency = ? AND date = ?
`

type GetExchangeRateParams struct {
	Currency string `json:"currency"`
	Date     string `json:"date"`
}

func (q *Queries) GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRowContext(ctx, getExchangeRate, arg.Currency, arg.Date)
	var i ExchangeRate
	err := row.Scan(
		&i.Currency,
		&i.Date,
		&i.RateNok,
		&i.Source,
	)
	return i, err
}

const getNearestExchangeRate = `-- name: GetNearestExchangeRate :one
SELECT currency, date, rate_nok, source FROM exchange_rates
WHERE currency = ? AND date <= ?
ORDER BY date DESC
LIMIT 1
`

type GetNearestExchangeRateParams struct {
	Currency string `json:"currency"`
	Date     string `json:"date"`
}

func (q *Queries) GetNearestExchangeRate(ctx context.Context, arg GetNearestExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRowContext(ctx, getNearestExchangeRate, arg.Currency, arg.Date)
	var i ExchangeRate
	err := row.Scan(
		&i.Currency,
		&i.Date,
		&i.RateNok,
		&i.Source,
	)
	return i, err
}

const listExchangeRates = `-- name: ListExchangeRates :many
SELECT currency, date, rate_nok, source FROM exchange_rates WHERE currency = ? ORDER BY date DESC
`

func (q *Queries) ListExchangeRates(ctx context.Context, currency string) ([]ExchangeRate, error) {
	rows, err := q.db.QueryContext(ctx, listExchangeRates, currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.Currency,
			&i.Date,
			&i.RateNok,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rates (currency, date, rate_nok, source)
VALUES (?, ?, ?, ?)
ON CONFLICT(currency, date) DO UPDATE SET rate_nok = excluded.rate_nok, source = excluded.source
`

type UpsertExchangeRateParams struct {
	Currency string  `json:"currency"`
	Date     string  `json:"date"`
	RateNok  float64 `json:"rate_nok"`
	Source   string  `json:"source"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.ExecContext(ctx, upsertExchangeRate,
		arg.Currency,
		arg.Date,
		arg.RateNok,
		arg.Source,
	)
	return err
}
