// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"
	"database/sql"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
  date, description, amount_nok, category, deductible_pct, deductible_nok,
  receipt_id, tax_year, notes
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, date, description, amount_nok, category, deductible_pct, deductible_nok, receipt_id, tax_year, notes, created_at
`

type CreateExpenseParams struct {
	Date          string         `json:"date"`
	Description   string         `json:"description"`
	AmountNok     float64        `json:"amount_nok"`
	Category      string         `json:"category"`
	DeductiblePct float64        `json:"deductible_pct"`
	DeductibleNok float64        `json:"deductible_nok"`
	ReceiptID     sql.NullInt64  `json:"receipt_id"`
	TaxYear       int64          `json:"tax_year"`
	Notes         sql.NullString `json:"notes"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.Date,
		arg.Description,
		arg.AmountNok,
		arg.Category,
		arg.DeductiblePct,
		arg.DeductibleNok,
		arg.ReceiptID,
		arg.TaxYear,
		arg.Notes,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.AmountNok,
		&i.Category,
		&i.DeductiblePct,
		&i.DeductibleNok,
		&i.ReceiptID,
		&i.TaxYear,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = ?
`

func (q *Queries) DeleteExpense(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, id)
	return err
}

const getExpense = `-- name: GetExpense :one
SELECT id, date, description, amount_nok, category, deductible_pct, deductible_nok, receipt_id, tax_year, notes, created_at FROM expenses WHERE id = ?
`

func (q *Queries) GetExpense(ctx context.Context, id int64) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.AmountNok,
		&i.Category,
		&i.DeductiblePct,
		&i.DeductibleNok,
		&i.ReceiptID,
		&i.TaxYear,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listAllExpenses = `-- name: ListAllExpenses :many
SELECT id, date, description, amount_nok, category, deductible_pct, deductible_nok, receipt_id, tax_year, notes, created_at FROM expenses ORDER BY date DESC, id DESC
`

func (q *Queries) ListAllExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listAllExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.AmountNok,
			&i.Category,
			&i.DeductiblePct,
			&i.DeductibleNok,
			&i.ReceiptID,
			&i.TaxYear,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByYear = `-- name: ListExpensesByYear :many
SELECT id, date, description, amount_nok, category, deductible_pct, deductible_nok, receipt_id, tax_year, notes, created_at FROM expenses WHERE tax_year = ? ORDER BY date DESC, id DESC
`

func (q *Queries) ListExpensesByYear(ctx context.Context, taxYear int64) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByYear, taxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.AmountNok,
			&i.Category,
			&i.DeductiblePct,
			&i.DeductibleNok,
			&i.ReceiptID,
			&i.TaxYear,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDeductibleByYear = `-- name: SumDeductibleByYear :one
SELECT COALESCE(SUM(deductible_nok), 0) AS total FROM expenses WHERE tax_year = ?
`

func (q *Queries) SumDeductibleByYear(ctx context.Context, taxYear int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumDeductibleByYear, taxYear)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumExpensesByCategory = `-- name: SumExpensesByCategory :many
SELECT category,
       COALESCE(SUM(amount_nok), 0) AS total,
       COALESCE(SUM(deductible_nok), 0) AS deductible
FROM expenses WHERE tax_year = ?
GROUP BY category ORDER BY deductible DESC
`

type SumExpensesByCategoryRow struct {
	Category   string      `json:"category"`
	Total      interface{} `json:"total"`
	Deductible interface{} `json:"deductible"`
}

func (q *Queries) SumExpensesByCategory(ctx context.Context, taxYear int64) ([]SumExpensesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, sumExpensesByCategory, taxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByCategoryRow{}
	for rows.Next() {
		var i SumExpensesByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total, &i.Deductible); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseReceipt = `-- name: UpdateExpenseReceipt :exec
UPDATE expenses SET receipt_id = ? WHERE id = ?
`

type UpdateExpenseReceiptParams struct {
	ReceiptID sql.NullInt64 `json:"receipt_id"`
	ID        int64         `json:"id"`
}

func (q *Queries) UpdateExpenseReceipt(ctx context.Context, arg UpdateExpenseReceiptParams) error {
	_, err := q.db.ExecContext(ctx, updateExpenseReceipt, arg.ReceiptID, arg.ID)
	return err
}
