// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"
	"database/sql"
)

func scanExpense(s interface {
	Scan(...any) error
}) (Expense, error) {
	var i Expense
	err := s.Scan(
		&i.ID, &i.Date, &i.Description, &i.AmountOrig, &i.Currency, &i.ExchangeRate,
		&i.RateDate, &i.CountryCode, &i.AmountNok, &i.Category, &i.DeductiblePct,
		&i.DeductibleNok, &i.ReceiptID, &i.IncomeID, &i.TaxYear, &i.Notes, &i.CreatedAt,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
  date, description, amount_orig, currency, exchange_rate, rate_date,
  country_code, amount_nok, category, deductible_pct, deductible_nok,
  receipt_id, income_id, tax_year, notes
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, date, description, amount_orig, currency, exchange_rate, rate_date, country_code, amount_nok, category, deductible_pct, deductible_nok, receipt_id, income_id, tax_year, notes, created_at
`

type CreateExpenseParams struct {
	Date          string          `json:"date"`
	Description   string          `json:"description"`
	AmountOrig    float64         `json:"amount_orig"`
	Currency      string          `json:"currency"`
	ExchangeRate  sql.NullFloat64 `json:"exchange_rate"`
	RateDate      sql.NullString  `json:"rate_date"`
	CountryCode   string          `json:"country_code"`
	AmountNok     float64         `json:"amount_nok"`
	Category      string          `json:"category"`
	DeductiblePct float64         `json:"deductible_pct"`
	DeductibleNok float64         `json:"deductible_nok"`
	ReceiptID     sql.NullInt64   `json:"receipt_id"`
	IncomeID      sql.NullInt64   `json:"income_id"`
	TaxYear       int64           `json:"tax_year"`
	Notes         sql.NullString  `json:"notes"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.Date, arg.Description, arg.AmountOrig, arg.Currency, arg.ExchangeRate,
		arg.RateDate, arg.CountryCode, arg.AmountNok, arg.Category, arg.DeductiblePct,
		arg.DeductibleNok, arg.ReceiptID, arg.IncomeID, arg.TaxYear, arg.Notes,
	)
	return scanExpense(row)
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = ?
`

func (q *Queries) DeleteExpense(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, id)
	return err
}

const getExpense = `-- name: GetExpense :one
SELECT id, date, description, amount_orig, currency, exchange_rate, rate_date, country_code, amount_nok, category, deductible_pct, deductible_nok, receipt_id, income_id, tax_year, notes, created_at FROM expenses WHERE id = ?
`

func (q *Queries) GetExpense(ctx context.Context, id int64) (Expense, error) {
	return scanExpense(q.db.QueryRowContext(ctx, getExpense, id))
}

const listAllExpenses = `-- name: ListAllExpenses :many
SELECT id, date, description, amount_orig, currency, exchange_rate, rate_date, country_code, amount_nok, category, deductible_pct, deductible_nok, receipt_id, income_id, tax_year, notes, created_at FROM expenses ORDER BY date DESC, id DESC
`

func (q *Queries) ListAllExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listAllExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		i, err := scanExpense(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	return items, rows.Err()
}

const listExpensesByYear = `-- name: ListExpensesByYear :many
SELECT id, date, description, amount_orig, currency, exchange_rate, rate_date, country_code, amount_nok, category, deductible_pct, deductible_nok, receipt_id, income_id, tax_year, notes, created_at FROM expenses WHERE tax_year = ? ORDER BY date DESC, id DESC
`

func (q *Queries) ListExpensesByYear(ctx context.Context, taxYear int64) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByYear, taxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		i, err := scanExpense(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	return items, rows.Err()
}

const listExpensesByIncome = `-- name: ListExpensesByIncome :many
SELECT id, date, description, amount_orig, currency, exchange_rate, rate_date, country_code, amount_nok, category, deductible_pct, deductible_nok, receipt_id, income_id, tax_year, notes, created_at FROM expenses WHERE income_id = ? ORDER BY date, id
`

func (q *Queries) ListExpensesByIncome(ctx context.Context, incomeID sql.NullInt64) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByIncome, incomeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		i, err := scanExpense(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	return items, rows.Err()
}

const sumDeductibleByYear = `-- name: SumDeductibleByYear :one
SELECT COALESCE(SUM(deductible_nok), 0) AS total FROM expenses WHERE tax_year = ?
`

func (q *Queries) SumDeductibleByYear(ctx context.Context, taxYear int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumDeductibleByYear, taxYear)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumExpensesByCategory = `-- name: SumExpensesByCategory :many
SELECT category,
       COALESCE(SUM(amount_nok), 0) AS total,
       COALESCE(SUM(deductible_nok), 0) AS deductible
FROM expenses WHERE tax_year = ?
GROUP BY category ORDER BY deductible DESC
`

type SumExpensesByCategoryRow struct {
	Category   string      `json:"category"`
	Total      interface{} `json:"total"`
	Deductible interface{} `json:"deductible"`
}

func (q *Queries) SumExpensesByCategory(ctx context.Context, taxYear int64) ([]SumExpensesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, sumExpensesByCategory, taxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByCategoryRow{}
	for rows.Next() {
		var i SumExpensesByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total, &i.Deductible); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	return items, rows.Err()
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses SET
  date = ?, description = ?, amount_orig = ?, currency = ?, exchange_rate = ?,
  rate_date = ?, country_code = ?, amount_nok = ?, category = ?,
  deductible_pct = ?, deductible_nok = ?, income_id = ?, tax_year = ?, notes = ?
WHERE id = ?
RETURNING id, date, description, amount_orig, currency, exchange_rate, rate_date, country_code, amount_nok, category, deductible_pct, deductible_nok, receipt_id, income_id, tax_year, notes, created_at
`

type UpdateExpenseParams struct {
	Date          string          `json:"date"`
	Description   string          `json:"description"`
	AmountOrig    float64         `json:"amount_orig"`
	Currency      string          `json:"currency"`
	ExchangeRate  sql.NullFloat64 `json:"exchange_rate"`
	RateDate      sql.NullString  `json:"rate_date"`
	CountryCode   string          `json:"country_code"`
	AmountNok     float64         `json:"amount_nok"`
	Category      string          `json:"category"`
	DeductiblePct float64         `json:"deductible_pct"`
	DeductibleNok float64         `json:"deductible_nok"`
	IncomeID      sql.NullInt64   `json:"income_id"`
	TaxYear       int64           `json:"tax_year"`
	Notes         sql.NullString  `json:"notes"`
	ID            int64           `json:"id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense,
		arg.Date, arg.Description, arg.AmountOrig, arg.Currency, arg.ExchangeRate,
		arg.RateDate, arg.CountryCode, arg.AmountNok, arg.Category, arg.DeductiblePct,
		arg.DeductibleNok, arg.IncomeID, arg.TaxYear, arg.Notes, arg.ID,
	)
	return scanExpense(row)
}

const updateExpenseReceipt = `-- name: UpdateExpenseReceipt :exec
UPDATE expenses SET receipt_id = ? WHERE id = ?
`

type UpdateExpenseReceiptParams struct {
	ReceiptID sql.NullInt64 `json:"receipt_id"`
	ID        int64         `json:"id"`
}

func (q *Queries) UpdateExpenseReceipt(ctx context.Context, arg UpdateExpenseReceiptParams) error {
	_, err := q.db.ExecContext(ctx, updateExpenseReceipt, arg.ReceiptID, arg.ID)
	return err
}
