// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foreign_tax.sql

package db

import (
	"context"
	"database/sql"
)

const deleteForeignTaxCredit = `-- name: DeleteForeignTaxCredit :exec
DELETE FROM foreign_tax_credits WHERE id = ?
`

func (q *Queries) DeleteForeignTaxCredit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteForeignTaxCredit, id)
	return err
}

const getForeignTaxCredit = `-- name: GetForeignTaxCredit :one
SELECT id, tax_year, country_code, country_name, income_nok, foreign_tax_orig, foreign_currency, foreign_tax_nok, max_credit_nok, utilized_nok, carryforward_nok, tax_finalized_abroad, documentation_type, legal_basis, rf1147_ready, notes, created_at FROM foreign_tax_credits WHERE tax_year = ? AND country_code = ?
`

type GetForeignTaxCreditParams struct {
	TaxYear     int64  `json:"tax_year"`
	CountryCode string `json:"country_code"`
}

func (q *Queries) GetForeignTaxCredit(ctx context.Context, arg GetForeignTaxCreditParams) (ForeignTaxCredit, error) {
	row := q.db.QueryRowContext(ctx, getForeignTaxCredit, arg.TaxYear, arg.CountryCode)
	var i ForeignTaxCredit
	err := row.Scan(
		&i.ID,
		&i.TaxYear,
		&i.CountryCode,
		&i.CountryName,
		&i.IncomeNok,
		&i.ForeignTaxOrig,
		&i.ForeignCurrency,
		&i.ForeignTaxNok,
		&i.MaxCreditNok,
		&i.UtilizedNok,
		&i.CarryforwardNok,
		&i.TaxFinalizedAbroad,
		&i.DocumentationType,
		&i.LegalBasis,
		&i.Rf1147Ready,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listAllForeignTaxCredits = `-- name: ListAllForeignTaxCredits :many
SELECT id, tax_year, country_code, country_name, income_nok, foreign_tax_orig, foreign_currency, foreign_tax_nok, max_credit_nok, utilized_nok, carryforward_nok, tax_finalized_abroad, documentation_type, legal_basis, rf1147_ready, notes, created_at FROM foreign_tax_credits ORDER BY tax_year DESC, country_name
`

func (q *Queries) ListAllForeignTaxCredits(ctx context.Context) ([]ForeignTaxCredit, error) {
	rows, err := q.db.QueryContext(ctx, listAllForeignTaxCredits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForeignTaxCredit{}
	for rows.Next() {
		var i ForeignTaxCredit
		if err := rows.Scan(
			&i.ID,
			&i.TaxYear,
			&i.CountryCode,
			&i.CountryName,
			&i.IncomeNok,
			&i.ForeignTaxOrig,
			&i.ForeignCurrency,
			&i.ForeignTaxNok,
			&i.MaxCreditNok,
			&i.UtilizedNok,
			&i.CarryforwardNok,
			&i.TaxFinalizedAbroad,
			&i.DocumentationType,
			&i.LegalBasis,
			&i.Rf1147Ready,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForeignTaxCreditsByYear = `-- name: ListForeignTaxCreditsByYear :many
SELECT id, tax_year, country_code, country_name, income_nok, foreign_tax_orig, foreign_currency, foreign_tax_nok, max_credit_nok, utilized_nok, carryforward_nok, tax_finalized_abroad, documentation_type, legal_basis, rf1147_ready, notes, created_at FROM foreign_tax_credits WHERE tax_year = ? ORDER BY country_name
`

func (q *Queries) ListForeignTaxCreditsByYear(ctx context.Context, taxYear int64) ([]ForeignTaxCredit, error) {
	rows, err := q.db.QueryContext(ctx, listForeignTaxCreditsByYear, taxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForeignTaxCredit{}
	for rows.Next() {
		var i ForeignTaxCredit
		if err := rows.Scan(
			&i.ID,
			&i.TaxYear,
			&i.CountryCode,
			&i.CountryName,
			&i.IncomeNok,
			&i.ForeignTaxOrig,
			&i.ForeignCurrency,
			&i.ForeignTaxNok,
			&i.MaxCreditNok,
			&i.UtilizedNok,
			&i.CarryforwardNok,
			&i.TaxFinalizedAbroad,
			&i.DocumentationType,
			&i.LegalBasis,
			&i.Rf1147Ready,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertForeignTaxCredit = `-- name: UpsertForeignTaxCredit :one
INSERT INTO foreign_tax_credits (
  tax_year, country_code, country_name, income_nok, foreign_tax_orig,
  foreign_currency, foreign_tax_nok, max_credit_nok, utilized_nok,
  carryforward_nok, tax_finalized_abroad, documentation_type, legal_basis,
  rf1147_ready, notes
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(tax_year, country_code) DO UPDATE SET
  country_name = excluded.country_name,
  income_nok = excluded.income_nok,
  foreign_tax_orig = excluded.foreign_tax_orig,
  foreign_currency = excluded.foreign_currency,
  foreign_tax_nok = excluded.foreign_tax_nok,
  max_credit_nok = excluded.max_credit_nok,
  utilized_nok = excluded.utilized_nok,
  carryforward_nok = excluded.carryforward_nok,
  tax_finalized_abroad = excluded.tax_finalized_abroad,
  documentation_type = excluded.documentation_type,
  legal_basis = excluded.legal_basis,
  rf1147_ready = excluded.rf1147_ready,
  notes = excluded.notes
RETURNING id, tax_year, country_code, country_name, income_nok, foreign_tax_orig, foreign_currency, foreign_tax_nok, max_credit_nok, utilized_nok, carryforward_nok, tax_finalized_abroad, documentation_type, legal_basis, rf1147_ready, notes, created_at
`

type UpsertForeignTaxCreditParams struct {
	TaxYear            int64           `json:"tax_year"`
	CountryCode        string          `json:"country_code"`
	CountryName        string          `json:"country_name"`
	IncomeNok          float64         `json:"income_nok"`
	ForeignTaxOrig     float64         `json:"foreign_tax_orig"`
	ForeignCurrency    string          `json:"foreign_currency"`
	ForeignTaxNok      float64         `json:"foreign_tax_nok"`
	MaxCreditNok       sql.NullFloat64 `json:"max_credit_nok"`
	UtilizedNok        sql.NullFloat64 `json:"utilized_nok"`
	CarryforwardNok    sql.NullFloat64 `json:"carryforward_nok"`
	TaxFinalizedAbroad sql.NullInt64   `json:"tax_finalized_abroad"`
	DocumentationType  sql.NullString  `json:"documentation_type"`
	LegalBasis         sql.NullString  `json:"legal_basis"`
	Rf1147Ready        sql.NullInt64   `json:"rf1147_ready"`
	Notes              sql.NullString  `json:"notes"`
}

func (q *Queries) UpsertForeignTaxCredit(ctx context.Context, arg UpsertForeignTaxCreditParams) (ForeignTaxCredit, error) {
	row := q.db.QueryRowContext(ctx, upsertForeignTaxCredit,
		arg.TaxYear,
		arg.CountryCode,
		arg.CountryName,
		arg.IncomeNok,
		arg.ForeignTaxOrig,
		arg.ForeignCurrency,
		arg.ForeignTaxNok,
		arg.MaxCreditNok,
		arg.UtilizedNok,
		arg.CarryforwardNok,
		arg.TaxFinalizedAbroad,
		arg.DocumentationType,
		arg.LegalBasis,
		arg.Rf1147Ready,
		arg.Notes,
	)
	var i ForeignTaxCredit
	err := row.Scan(
		&i.ID,
		&i.TaxYear,
		&i.CountryCode,
		&i.CountryName,
		&i.IncomeNok,
		&i.ForeignTaxOrig,
		&i.ForeignCurrency,
		&i.ForeignTaxNok,
		&i.MaxCreditNok,
		&i.UtilizedNok,
		&i.CarryforwardNok,
		&i.TaxFinalizedAbroad,
		&i.DocumentationType,
		&i.LegalBasis,
		&i.Rf1147Ready,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
