// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: income.sql

package db

import (
	"context"
	"database/sql"
)

const aggregateForeignIncomeByYear = `-- name: AggregateForeignIncomeByYear :many
SELECT i.country_code,
       COALESCE(SUM(i.amount_nok), 0) AS income_nok,
       COALESCE(SUM(t.tax_orig), 0) AS foreign_tax_orig,
       COALESCE(SUM(t.tax_nok), 0) AS foreign_tax_nok
FROM income i
LEFT JOIN (
  SELECT income_id,
         SUM(amount_orig) AS tax_orig,
         SUM(amount_nok) AS tax_nok
  FROM income_foreign_taxes
  WHERE treatment = 'credit'
  GROUP BY income_id
) t ON t.income_id = i.id
WHERE i.tax_year = ? AND i.country_code <> 'NO'
GROUP BY i.country_code
`

type AggregateForeignIncomeByYearRow struct {
	CountryCode    string      `json:"country_code"`
	IncomeNok      interface{} `json:"income_nok"`
	ForeignTaxOrig interface{} `json:"foreign_tax_orig"`
	ForeignTaxNok  interface{} `json:"foreign_tax_nok"`
}

func (q *Queries) AggregateForeignIncomeByYear(ctx context.Context, taxYear int64) ([]AggregateForeignIncomeByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, aggregateForeignIncomeByYear, taxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateForeignIncomeByYearRow{}
	for rows.Next() {
		var i AggregateForeignIncomeByYearRow
		if err := rows.Scan(
			&i.CountryCode,
			&i.IncomeNok,
			&i.ForeignTaxOrig,
			&i.ForeignTaxNok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumForeignTaxByTreatmentYear = `-- name: SumForeignTaxByTreatmentYear :many
SELECT t.treatment, COALESCE(SUM(t.amount_nok), 0) AS total
FROM income_foreign_taxes t
JOIN income i ON i.id = t.income_id
WHERE i.tax_year = ?
GROUP BY t.treatment
`

type SumForeignTaxByTreatmentYearRow struct {
	Treatment string      `json:"treatment"`
	Total     interface{} `json:"total"`
}

func (q *Queries) SumForeignTaxByTreatmentYear(ctx context.Context, taxYear int64) ([]SumForeignTaxByTreatmentYearRow, error) {
	rows, err := q.db.QueryContext(ctx, sumForeignTaxByTreatmentYear, taxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumForeignTaxByTreatmentYearRow{}
	for rows.Next() {
		var i SumForeignTaxByTreatmentYearRow
		if err := rows.Scan(&i.Treatment, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForeignTaxLinesByYearTreatment = `-- name: ListForeignTaxLinesByYearTreatment :many
SELECT t.id, t.income_id, t.tax_type, t.amount_orig, t.currency, t.amount_nok,
       i.date AS income_date, i.description AS income_description
FROM income_foreign_taxes t
JOIN income i ON i.id = t.income_id
WHERE i.tax_year = ? AND t.treatment = ?
ORDER BY i.date, t.id
`

type ListForeignTaxLinesByYearTreatmentParams struct {
	TaxYear   int64  `json:"tax_year"`
	Treatment string `json:"treatment"`
}

type ListForeignTaxLinesByYearTreatmentRow struct {
	ID                int64   `json:"id"`
	IncomeID          int64   `json:"income_id"`
	TaxType           string  `json:"tax_type"`
	AmountOrig        float64 `json:"amount_orig"`
	Currency          string  `json:"currency"`
	AmountNok         float64 `json:"amount_nok"`
	IncomeDate        string  `json:"income_date"`
	IncomeDescription string  `json:"income_description"`
}

func (q *Queries) ListForeignTaxLinesByYearTreatment(ctx context.Context, arg ListForeignTaxLinesByYearTreatmentParams) ([]ListForeignTaxLinesByYearTreatmentRow, error) {
	rows, err := q.db.QueryContext(ctx, listForeignTaxLinesByYearTreatment, arg.TaxYear, arg.Treatment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForeignTaxLinesByYearTreatmentRow{}
	for rows.Next() {
		var i ListForeignTaxLinesByYearTreatmentRow
		if err := rows.Scan(
			&i.ID,
			&i.IncomeID,
			&i.TaxType,
			&i.AmountOrig,
			&i.Currency,
			&i.AmountNok,
			&i.IncomeDate,
			&i.IncomeDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createIncome = `-- name: CreateIncome :one
INSERT INTO income (
  date, description, amount_orig, currency, exchange_rate, rate_date,
  amount_nok, category, client, country_code,
  foreign_tax_paid, receipt_id, tax_year, notes
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, date, description, amount_orig, currency, exchange_rate, rate_date, amount_nok, category, client, country_code, foreign_tax_paid, receipt_id, tax_year, notes, created_at
`

type CreateIncomeParams struct {
	Date           string          `json:"date"`
	Description    string          `json:"description"`
	AmountOrig     float64         `json:"amount_orig"`
	Currency       string          `json:"currency"`
	ExchangeRate   sql.NullFloat64 `json:"exchange_rate"`
	RateDate       sql.NullString  `json:"rate_date"`
	AmountNok      float64         `json:"amount_nok"`
	Category       string          `json:"category"`
	Client         sql.NullString  `json:"client"`
	CountryCode    string          `json:"country_code"`
	ForeignTaxPaid int64           `json:"foreign_tax_paid"`
	ReceiptID      sql.NullInt64   `json:"receipt_id"`
	TaxYear        int64           `json:"tax_year"`
	Notes          sql.NullString  `json:"notes"`
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRowContext(ctx, createIncome,
		arg.Date,
		arg.Description,
		arg.AmountOrig,
		arg.Currency,
		arg.ExchangeRate,
		arg.RateDate,
		arg.AmountNok,
		arg.Category,
		arg.Client,
		arg.CountryCode,
		arg.ForeignTaxPaid,
		arg.ReceiptID,
		arg.TaxYear,
		arg.Notes,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.AmountOrig,
		&i.Currency,
		&i.ExchangeRate,
		&i.RateDate,
		&i.AmountNok,
		&i.Category,
		&i.Client,
		&i.CountryCode,
		&i.ForeignTaxPaid,
		&i.ReceiptID,
		&i.TaxYear,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createIncomeForeignTax = `-- name: CreateIncomeForeignTax :one
INSERT INTO income_foreign_taxes (
  income_id, tax_type, amount_orig, currency, amount_nok, treatment
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, income_id, tax_type, amount_orig, currency, amount_nok, treatment
`

type CreateIncomeForeignTaxParams struct {
	IncomeID   int64   `json:"income_id"`
	TaxType    string  `json:"tax_type"`
	AmountOrig float64 `json:"amount_orig"`
	Currency   string  `json:"currency"`
	AmountNok  float64 `json:"amount_nok"`
	Treatment  string  `json:"treatment"`
}

func (q *Queries) CreateIncomeForeignTax(ctx context.Context, arg CreateIncomeForeignTaxParams) (IncomeForeignTax, error) {
	row := q.db.QueryRowContext(ctx, createIncomeForeignTax,
		arg.IncomeID,
		arg.TaxType,
		arg.AmountOrig,
		arg.Currency,
		arg.AmountNok,
		arg.Treatment,
	)
	var i IncomeForeignTax
	err := row.Scan(
		&i.ID,
		&i.IncomeID,
		&i.TaxType,
		&i.AmountOrig,
		&i.Currency,
		&i.AmountNok,
		&i.Treatment,
	)
	return i, err
}

const deleteIncome = `-- name: DeleteIncome :exec
DELETE FROM income WHERE id = ?
`

func (q *Queries) DeleteIncome(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIncome, id)
	return err
}

const deleteIncomeForeignTaxesByIncome = `-- name: DeleteIncomeForeignTaxesByIncome :exec
DELETE FROM income_foreign_taxes WHERE income_id = ?
`

func (q *Queries) DeleteIncomeForeignTaxesByIncome(ctx context.Context, incomeID int64) error {
	_, err := q.db.ExecContext(ctx, deleteIncomeForeignTaxesByIncome, incomeID)
	return err
}

const distinctClients = `-- name: DistinctClients :many
SELECT DISTINCT client FROM income
WHERE client IS NOT NULL AND client <> ''
ORDER BY client
`

func (q *Queries) DistinctClients(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, distinctClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var client sql.NullString
		if err := rows.Scan(&client); err != nil {
			return nil, err
		}
		items = append(items, client)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncome = `-- name: GetIncome :one
SELECT id, date, description, amount_orig, currency, exchange_rate, rate_date, amount_nok, category, client, country_code, foreign_tax_paid, receipt_id, tax_year, notes, created_at FROM income WHERE id = ?
`

func (q *Queries) GetIncome(ctx context.Context, id int64) (Income, error) {
	row := q.db.QueryRowContext(ctx, getIncome, id)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.AmountOrig,
		&i.Currency,
		&i.ExchangeRate,
		&i.RateDate,
		&i.AmountNok,
		&i.Category,
		&i.Client,
		&i.CountryCode,
		&i.ForeignTaxPaid,
		&i.ReceiptID,
		&i.TaxYear,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listAllIncome = `-- name: ListAllIncome :many
SELECT id, date, description, amount_orig, currency, exchange_rate, rate_date, amount_nok, category, client, country_code, foreign_tax_paid, receipt_id, tax_year, notes, created_at FROM income ORDER BY date DESC, id DESC
`

func (q *Queries) ListAllIncome(ctx context.Context) ([]Income, error) {
	rows, err := q.db.QueryContext(ctx, listAllIncome)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Income{}
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.AmountOrig,
			&i.Currency,
			&i.ExchangeRate,
			&i.RateDate,
			&i.AmountNok,
			&i.Category,
			&i.Client,
			&i.CountryCode,
			&i.ForeignTaxPaid,
			&i.ReceiptID,
			&i.TaxYear,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllIncomeForeignTaxes = `-- name: ListAllIncomeForeignTaxes :many
SELECT id, income_id, tax_type, amount_orig, currency, amount_nok, treatment FROM income_foreign_taxes ORDER BY income_id, id
`

func (q *Queries) ListAllIncomeForeignTaxes(ctx context.Context) ([]IncomeForeignTax, error) {
	rows, err := q.db.QueryContext(ctx, listAllIncomeForeignTaxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncomeForeignTax{}
	for rows.Next() {
		var i IncomeForeignTax
		if err := rows.Scan(
			&i.ID,
			&i.IncomeID,
			&i.TaxType,
			&i.AmountOrig,
			&i.Currency,
			&i.AmountNok,
			&i.Treatment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeByCountryYear = `-- name: ListIncomeByCountryYear :many
SELECT id, date, description, amount_orig, currency, exchange_rate, rate_date, amount_nok, category, client, country_code, foreign_tax_paid, receipt_id, tax_year, notes, created_at FROM income WHERE country_code = ? AND tax_year = ? ORDER BY date
`

type ListIncomeByCountryYearParams struct {
	CountryCode string `json:"country_code"`
	TaxYear     int64  `json:"tax_year"`
}

func (q *Queries) ListIncomeByCountryYear(ctx context.Context, arg ListIncomeByCountryYearParams) ([]Income, error) {
	rows, err := q.db.QueryContext(ctx, listIncomeByCountryYear, arg.CountryCode, arg.TaxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Income{}
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.AmountOrig,
			&i.Currency,
			&i.ExchangeRate,
			&i.RateDate,
			&i.AmountNok,
			&i.Category,
			&i.Client,
			&i.CountryCode,
			&i.ForeignTaxPaid,
			&i.ReceiptID,
			&i.TaxYear,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeByYear = `-- name: ListIncomeByYear :many
SELECT id, date, description, amount_orig, currency, exchange_rate, rate_date, amount_nok, category, client, country_code, foreign_tax_paid, receipt_id, tax_year, notes, created_at FROM income WHERE tax_year = ? ORDER BY date DESC, id DESC
`

func (q *Queries) ListIncomeByYear(ctx context.Context, taxYear int64) ([]Income, error) {
	rows, err := q.db.QueryContext(ctx, listIncomeByYear, taxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Income{}
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.AmountOrig,
			&i.Currency,
			&i.ExchangeRate,
			&i.RateDate,
			&i.AmountNok,
			&i.Category,
			&i.Client,
			&i.CountryCode,
			&i.ForeignTaxPaid,
			&i.ReceiptID,
			&i.TaxYear,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeForeignTaxes = `-- name: ListIncomeForeignTaxes :many
SELECT id, income_id, tax_type, amount_orig, currency, amount_nok, treatment FROM income_foreign_taxes WHERE income_id = ? ORDER BY id
`

func (q *Queries) ListIncomeForeignTaxes(ctx context.Context, incomeID int64) ([]IncomeForeignTax, error) {
	rows, err := q.db.QueryContext(ctx, listIncomeForeignTaxes, incomeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncomeForeignTax{}
	for rows.Next() {
		var i IncomeForeignTax
		if err := rows.Scan(
			&i.ID,
			&i.IncomeID,
			&i.TaxType,
			&i.AmountOrig,
			&i.Currency,
			&i.AmountNok,
			&i.Treatment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumIncomeByCategory = `-- name: SumIncomeByCategory :many
SELECT category, COALESCE(SUM(amount_nok), 0) AS total
FROM income WHERE tax_year = ?
GROUP BY category ORDER BY total DESC
`

type SumIncomeByCategoryRow struct {
	Category string      `json:"category"`
	Total    interface{} `json:"total"`
}

func (q *Queries) SumIncomeByCategory(ctx context.Context, taxYear int64) ([]SumIncomeByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, sumIncomeByCategory, taxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumIncomeByCategoryRow{}
	for rows.Next() {
		var i SumIncomeByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumIncomeNOKByYear = `-- name: SumIncomeNOKByYear :one
SELECT COALESCE(SUM(amount_nok), 0) AS total FROM income WHERE tax_year = ?
`

func (q *Queries) SumIncomeNOKByYear(ctx context.Context, taxYear int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumIncomeNOKByYear, taxYear)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE income SET
  date = ?, description = ?, amount_orig = ?, currency = ?, exchange_rate = ?,
  rate_date = ?, amount_nok = ?, category = ?, client = ?, country_code = ?,
  foreign_tax_paid = ?, tax_year = ?, notes = ?
WHERE id = ?
RETURNING id, date, description, amount_orig, currency, exchange_rate, rate_date, amount_nok, category, client, country_code, foreign_tax_paid, receipt_id, tax_year, notes, created_at
`

type UpdateIncomeParams struct {
	Date           string          `json:"date"`
	Description    string          `json:"description"`
	AmountOrig     float64         `json:"amount_orig"`
	Currency       string          `json:"currency"`
	ExchangeRate   sql.NullFloat64 `json:"exchange_rate"`
	RateDate       sql.NullString  `json:"rate_date"`
	AmountNok      float64         `json:"amount_nok"`
	Category       string          `json:"category"`
	Client         sql.NullString  `json:"client"`
	CountryCode    string          `json:"country_code"`
	ForeignTaxPaid int64           `json:"foreign_tax_paid"`
	TaxYear        int64           `json:"tax_year"`
	Notes          sql.NullString  `json:"notes"`
	ID             int64           `json:"id"`
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRowContext(ctx, updateIncome,
		arg.Date,
		arg.Description,
		arg.AmountOrig,
		arg.Currency,
		arg.ExchangeRate,
		arg.RateDate,
		arg.AmountNok,
		arg.Category,
		arg.Client,
		arg.CountryCode,
		arg.ForeignTaxPaid,
		arg.TaxYear,
		arg.Notes,
		arg.ID,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.AmountOrig,
		&i.Currency,
		&i.ExchangeRate,
		&i.RateDate,
		&i.AmountNok,
		&i.Category,
		&i.Client,
		&i.CountryCode,
		&i.ForeignTaxPaid,
		&i.ReceiptID,
		&i.TaxYear,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateIncomeReceipt = `-- name: UpdateIncomeReceipt :exec
UPDATE income SET receipt_id = ? WHERE id = ?
`

type UpdateIncomeReceiptParams struct {
	ReceiptID sql.NullInt64 `json:"receipt_id"`
	ID        int64         `json:"id"`
}

func (q *Queries) UpdateIncomeReceipt(ctx context.Context, arg UpdateIncomeReceiptParams) error {
	_, err := q.db.ExecContext(ctx, updateIncomeReceipt, arg.ReceiptID, arg.ID)
	return err
}
