// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ChangeLog struct {
	ID          int64          `json:"id"`
	Ts          string         `json:"ts"`
	Actor       string         `json:"actor"`
	Operation   string         `json:"operation"`
	Entity      string         `json:"entity"`
	EntityID    sql.NullInt64  `json:"entity_id"`
	BeforeJson  sql.NullString `json:"before_json"`
	AfterJson   sql.NullString `json:"after_json"`
	Description string         `json:"description"`
	RolledBack  int64          `json:"rolled_back"`
	RollbackOf  sql.NullInt64  `json:"rollback_of"`
}

type Config struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type CountryTaxRule struct {
	ID                     int64           `json:"id"`
	CountryCode            string          `json:"country_code"`
	CountryName            string          `json:"country_name"`
	EffectiveFrom          int64           `json:"effective_from"`
	EffectiveTo            sql.NullInt64   `json:"effective_to"`
	HasTaxTreaty           int64           `json:"has_tax_treaty"`
	TreatyInForceDate      sql.NullString  `json:"treaty_in_force_date"`
	TreatyMethod           sql.NullString  `json:"treaty_method"`
	TreatyReference        sql.NullString  `json:"treaty_reference"`
	TreatySourceUrl        sql.NullString  `json:"treaty_source_url"`
	StandardWithholdingPct sql.NullFloat64 `json:"standard_withholding_pct"`
	Notes                  sql.NullString  `json:"notes"`
	LastUpdated            string          `json:"last_updated"`
}

type CountryTaxType struct {
	ID                   int64           `json:"id"`
	CountryCode          string          `json:"country_code"`
	TaxTypeCode          string          `json:"tax_type_code"`
	TaxTypeName          string          `json:"tax_type_name"`
	Description          sql.NullString  `json:"description"`
	AppliesTo            sql.NullString  `json:"applies_to"`
	IsCreditableInNorway sql.NullInt64   `json:"is_creditable_in_norway"`
	Basis                sql.NullString  `json:"basis"`
	TypicalRatePct       sql.NullFloat64 `json:"typical_rate_pct"`
	EffectiveFrom        int64           `json:"effective_from"`
	EffectiveTo          sql.NullInt64   `json:"effective_to"`
}

type ExchangeRate struct {
	Currency string  `json:"currency"`
	Date     string  `json:"date"`
	RateNok  float64 `json:"rate_nok"`
	Source   string  `json:"source"`
}

type Expense struct {
	ID            int64          `json:"id"`
	Date          string         `json:"date"`
	Description   string         `json:"description"`
	AmountNok     float64        `json:"amount_nok"`
	Category      string         `json:"category"`
	DeductiblePct float64        `json:"deductible_pct"`
	DeductibleNok float64        `json:"deductible_nok"`
	ReceiptID     sql.NullInt64  `json:"receipt_id"`
	TaxYear       int64          `json:"tax_year"`
	Notes         sql.NullString `json:"notes"`
	CreatedAt     string         `json:"created_at"`
}

type ForeignTaxCredit struct {
	ID                 int64           `json:"id"`
	TaxYear            int64           `json:"tax_year"`
	CountryCode        string          `json:"country_code"`
	CountryName        string          `json:"country_name"`
	IncomeNok          float64         `json:"income_nok"`
	ForeignTaxOrig     float64         `json:"foreign_tax_orig"`
	ForeignCurrency    string          `json:"foreign_currency"`
	ForeignTaxNok      float64         `json:"foreign_tax_nok"`
	MaxCreditNok       sql.NullFloat64 `json:"max_credit_nok"`
	UtilizedNok        sql.NullFloat64 `json:"utilized_nok"`
	CarryforwardNok    sql.NullFloat64 `json:"carryforward_nok"`
	TaxFinalizedAbroad sql.NullInt64   `json:"tax_finalized_abroad"`
	DocumentationType  sql.NullString  `json:"documentation_type"`
	LegalBasis         sql.NullString  `json:"legal_basis"`
	Rf1147Ready        sql.NullInt64   `json:"rf1147_ready"`
	Notes              sql.NullString  `json:"notes"`
	CreatedAt          string          `json:"created_at"`
}

type Income struct {
	ID                 int64           `json:"id"`
	Date               string          `json:"date"`
	Description        string          `json:"description"`
	AmountOrig         float64         `json:"amount_orig"`
	Currency           string          `json:"currency"`
	ExchangeRate       sql.NullFloat64 `json:"exchange_rate"`
	RateDate           sql.NullString  `json:"rate_date"`
	AmountNok          float64         `json:"amount_nok"`
	Category           string          `json:"category"`
	Client             sql.NullString  `json:"client"`
	CountryCode        string          `json:"country_code"`
	ForeignTaxPaid     int64           `json:"foreign_tax_paid"`
	ForeignTaxOrig     sql.NullFloat64 `json:"foreign_tax_orig"`
	ForeignTaxCurrency sql.NullString  `json:"foreign_tax_currency"`
	ForeignTaxNok      sql.NullFloat64 `json:"foreign_tax_nok"`
	ForeignTaxType     sql.NullString  `json:"foreign_tax_type"`
	ReceiptID          sql.NullInt64   `json:"receipt_id"`
	TaxYear            int64           `json:"tax_year"`
	Notes              sql.NullString  `json:"notes"`
	CreatedAt          string          `json:"created_at"`
}

type Receipt struct {
	ID           int64          `json:"id"`
	Filename     string         `json:"filename"`
	OriginalName string         `json:"original_name"`
	MimeType     string         `json:"mime_type"`
	Title        sql.NullString `json:"title"`
	Description  sql.NullString `json:"description"`
	ParentKind   sql.NullString `json:"parent_kind"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	TaxYear      sql.NullInt64  `json:"tax_year"`
	UploadedAt   string         `json:"uploaded_at"`
}
