// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AggregateForeignIncomeByYear(ctx context.Context, taxYear int64) ([]AggregateForeignIncomeByYearRow, error)
	CountReceiptsByParent(ctx context.Context, arg CountReceiptsByParentParams) (int64, error)
	CreateChangeLog(ctx context.Context, arg CreateChangeLogParams) (ChangeLog, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error)
	CreateIncomeForeignTax(ctx context.Context, arg CreateIncomeForeignTaxParams) (IncomeForeignTax, error)
	CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error)
	DeleteConfig(ctx context.Context, key string) error
	DeleteExpense(ctx context.Context, id int64) error
	DeleteForeignTaxCredit(ctx context.Context, id int64) error
	DeleteIncome(ctx context.Context, id int64) error
	DeleteIncomeForeignTaxesByIncome(ctx context.Context, incomeID int64) error
	DeleteReceipt(ctx context.Context, id int64) error
	DistinctClients(ctx context.Context) ([]sql.NullString, error)
	GetChangeLog(ctx context.Context, id int64) (ChangeLog, error)
	GetConfig(ctx context.Context, key string) (string, error)
	GetCountryRule(ctx context.Context, arg GetCountryRuleParams) (CountryTaxRule, error)
	GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (ExchangeRate, error)
	GetExpense(ctx context.Context, id int64) (Expense, error)
	GetForeignTaxCredit(ctx context.Context, arg GetForeignTaxCreditParams) (ForeignTaxCredit, error)
	GetIncome(ctx context.Context, id int64) (Income, error)
	GetNearestExchangeRate(ctx context.Context, arg GetNearestExchangeRateParams) (ExchangeRate, error)
	GetReceipt(ctx context.Context, id int64) (Receipt, error)
	ListAllCountryTaxTypes(ctx context.Context) ([]CountryTaxType, error)
	ListAllExpenses(ctx context.Context) ([]Expense, error)
	ListAllForeignTaxCredits(ctx context.Context) ([]ForeignTaxCredit, error)
	ListAllIncome(ctx context.Context) ([]Income, error)
	ListAllIncomeForeignTaxes(ctx context.Context) ([]IncomeForeignTax, error)
	ListChangeLog(ctx context.Context, limit int64) ([]ChangeLog, error)
	ListConfig(ctx context.Context) ([]Config, error)
	ListCountryCodes(ctx context.Context) ([]ListCountryCodesRow, error)
	ListCountryRules(ctx context.Context) ([]CountryTaxRule, error)
	ListCountryTaxTypes(ctx context.Context, arg ListCountryTaxTypesParams) ([]CountryTaxType, error)
	ListExchangeRates(ctx context.Context, currency string) ([]ExchangeRate, error)
	ListExpensesByIncome(ctx context.Context, incomeID sql.NullInt64) ([]Expense, error)
	ListExpensesByYear(ctx context.Context, taxYear int64) ([]Expense, error)
	ListForeignTaxCreditsByYear(ctx context.Context, taxYear int64) ([]ForeignTaxCredit, error)
	ListForeignTaxLinesByYearTreatment(ctx context.Context, arg ListForeignTaxLinesByYearTreatmentParams) ([]ListForeignTaxLinesByYearTreatmentRow, error)
	ListIncomeByCountryYear(ctx context.Context, arg ListIncomeByCountryYearParams) ([]Income, error)
	ListIncomeByYear(ctx context.Context, taxYear int64) ([]Income, error)
	ListIncomeForeignTaxes(ctx context.Context, incomeID int64) ([]IncomeForeignTax, error)
	ListReceipts(ctx context.Context) ([]Receipt, error)
	ListReceiptsByParent(ctx context.Context, arg ListReceiptsByParentParams) ([]Receipt, error)
	MarkChangeRolledBack(ctx context.Context, id int64) error
	SetConfig(ctx context.Context, arg SetConfigParams) error
	SumDeductibleByYear(ctx context.Context, taxYear int64) (interface{}, error)
	SumExpensesByCategory(ctx context.Context, taxYear int64) ([]SumExpensesByCategoryRow, error)
	SumForeignTaxByTreatmentYear(ctx context.Context, taxYear int64) ([]SumForeignTaxByTreatmentYearRow, error)
	SumIncomeByCategory(ctx context.Context, taxYear int64) ([]SumIncomeByCategoryRow, error)
	SumIncomeNOKByYear(ctx context.Context, taxYear int64) (interface{}, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdateExpenseReceipt(ctx context.Context, arg UpdateExpenseReceiptParams) error
	UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error)
	UpdateIncomeReceipt(ctx context.Context, arg UpdateIncomeReceiptParams) error
	UpdateReceiptMeta(ctx context.Context, arg UpdateReceiptMetaParams) error
	UpdateReceiptParentLink(ctx context.Context, arg UpdateReceiptParentLinkParams) error
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error
	UpsertForeignTaxCredit(ctx context.Context, arg UpsertForeignTaxCreditParams) (ForeignTaxCredit, error)
}

var _ Querier = (*Queries)(nil)
