// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package db

import (
	"context"
	"database/sql"
)

const countUnlinkedReceipts = `-- name: CountUnlinkedReceipts :one
SELECT COUNT(*) AS cnt FROM receipts
WHERE id NOT IN (SELECT receipt_id FROM income WHERE receipt_id IS NOT NULL)
  AND id NOT IN (SELECT receipt_id FROM expenses WHERE receipt_id IS NOT NULL)
`

func (q *Queries) CountUnlinkedReceipts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnlinkedReceipts)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (filename, original_name, mime_type, tax_year)
VALUES (?, ?, ?, ?)
RETURNING id, filename, original_name, mime_type, tax_year, uploaded_at
`

type CreateReceiptParams struct {
	Filename     string        `json:"filename"`
	OriginalName string        `json:"original_name"`
	MimeType     string        `json:"mime_type"`
	TaxYear      sql.NullInt64 `json:"tax_year"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, createReceipt,
		arg.Filename,
		arg.OriginalName,
		arg.MimeType,
		arg.TaxYear,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.TaxYear,
		&i.UploadedAt,
	)
	return i, err
}

const deleteReceipt = `-- name: DeleteReceipt :exec
DELETE FROM receipts WHERE id = ?
`

func (q *Queries) DeleteReceipt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReceipt, id)
	return err
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, filename, original_name, mime_type, tax_year, uploaded_at FROM receipts WHERE id = ?
`

func (q *Queries) GetReceipt(ctx context.Context, id int64) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceipt, id)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.TaxYear,
		&i.UploadedAt,
	)
	return i, err
}

const listReceipts = `-- name: ListReceipts :many
SELECT id, filename, original_name, mime_type, tax_year, uploaded_at FROM receipts ORDER BY uploaded_at DESC, id DESC
`

func (q *Queries) ListReceipts(ctx context.Context) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.TaxYear,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlinkedReceipts = `-- name: ListUnlinkedReceipts :many
SELECT id, filename, original_name, mime_type, tax_year, uploaded_at FROM receipts
WHERE id NOT IN (SELECT receipt_id FROM income WHERE receipt_id IS NOT NULL)
  AND id NOT IN (SELECT receipt_id FROM expenses WHERE receipt_id IS NOT NULL)
ORDER BY uploaded_at DESC, id DESC
`

func (q *Queries) ListUnlinkedReceipts(ctx context.Context) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listUnlinkedReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.TaxYear,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
