// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package db

import (
	"context"
	"database/sql"
)

const countReceiptsByParent = `-- name: CountReceiptsByParent :one
SELECT COUNT(*) AS cnt FROM receipts WHERE parent_kind = ? AND parent_id = ?
`

type CountReceiptsByParentParams struct {
	ParentKind sql.NullString `json:"parent_kind"`
	ParentID   sql.NullInt64  `json:"parent_id"`
}

func (q *Queries) CountReceiptsByParent(ctx context.Context, arg CountReceiptsByParentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReceiptsByParent, arg.ParentKind, arg.ParentID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (filename, original_name, mime_type, title, description, parent_kind, parent_id, tax_year)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, filename, original_name, mime_type, title, description, parent_kind, parent_id, tax_year, uploaded_at
`

type CreateReceiptParams struct {
	Filename     string         `json:"filename"`
	OriginalName string         `json:"original_name"`
	MimeType     string         `json:"mime_type"`
	Title        sql.NullString `json:"title"`
	Description  sql.NullString `json:"description"`
	ParentKind   sql.NullString `json:"parent_kind"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	TaxYear      sql.NullInt64  `json:"tax_year"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, createReceipt,
		arg.Filename,
		arg.OriginalName,
		arg.MimeType,
		arg.Title,
		arg.Description,
		arg.ParentKind,
		arg.ParentID,
		arg.TaxYear,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.Title,
		&i.Description,
		&i.ParentKind,
		&i.ParentID,
		&i.TaxYear,
		&i.UploadedAt,
	)
	return i, err
}

const deleteReceipt = `-- name: DeleteReceipt :exec
DELETE FROM receipts WHERE id = ?
`

func (q *Queries) DeleteReceipt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReceipt, id)
	return err
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, filename, original_name, mime_type, title, description, parent_kind, parent_id, tax_year, uploaded_at FROM receipts WHERE id = ?
`

func (q *Queries) GetReceipt(ctx context.Context, id int64) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceipt, id)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.Title,
		&i.Description,
		&i.ParentKind,
		&i.ParentID,
		&i.TaxYear,
		&i.UploadedAt,
	)
	return i, err
}

const listReceipts = `-- name: ListReceipts :many
SELECT id, filename, original_name, mime_type, title, description, parent_kind, parent_id, tax_year, uploaded_at FROM receipts ORDER BY uploaded_at DESC, id DESC
`

func (q *Queries) ListReceipts(ctx context.Context) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.Title,
			&i.Description,
			&i.ParentKind,
			&i.ParentID,
			&i.TaxYear,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptsByParent = `-- name: ListReceiptsByParent :many
SELECT id, filename, original_name, mime_type, title, description, parent_kind, parent_id, tax_year, uploaded_at FROM receipts WHERE parent_kind = ? AND parent_id = ? ORDER BY id
`

type ListReceiptsByParentParams struct {
	ParentKind sql.NullString `json:"parent_kind"`
	ParentID   sql.NullInt64  `json:"parent_id"`
}

func (q *Queries) ListReceiptsByParent(ctx context.Context, arg ListReceiptsByParentParams) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptsByParent, arg.ParentKind, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.Title,
			&i.Description,
			&i.ParentKind,
			&i.ParentID,
			&i.TaxYear,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReceiptMeta = `-- name: UpdateReceiptMeta :exec
UPDATE receipts SET title = ?, description = ? WHERE id = ?
`

type UpdateReceiptMetaParams struct {
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateReceiptMeta(ctx context.Context, arg UpdateReceiptMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateReceiptMeta, arg.Title, arg.Description, arg.ID)
	return err
}

const updateReceiptParentLink = `-- name: UpdateReceiptParentLink :exec
UPDATE receipts SET parent_kind = ?, parent_id = ? WHERE id = ?
`

type UpdateReceiptParentLinkParams struct {
	ParentKind sql.NullString `json:"parent_kind"`
	ParentID   sql.NullInt64  `json:"parent_id"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateReceiptParentLink(ctx context.Context, arg UpdateReceiptParentLinkParams) error {
	_, err := q.db.ExecContext(ctx, updateReceiptParentLink, arg.ParentKind, arg.ParentID, arg.ID)
	return err
}
